### ISSUE TITLE
Bite is effectively the same as Claw

### ISSUE THREAD

**Issue by ribbybibby** [ribbybibby/Grimm-Journey#17]
BBW's Bite and Claw attacks, when playing, don't seem that different. Do we really need two close-range melee attacks?

**Comment by HoboMechanistic** [comment]
As discussed I believe according to the original design the Bite was supposed to give health back? We can still do this to validate the Bite attack. But as it stands it is pretty much the same as Claw.

**Comment by ribbybibby** [comment]
Agreed. We should change Bite so it is a unique attack.

+health with each attack would be a good idea

**Comment by ribbybibby** [comment]
Fixed in e2683c053e0e0193331a161f03e409a725f00928

- Bite now has a longer cooldown than Claw
- Bite now does considerably more damage than Claw
- Bite now returns a fraction (currently a fifth) of the enemy's total health

Additional notes:
- If BBW's health goes above the initial value, it decays back to max by an amount set in the Unity editor
