### ISSUE TITLE
Add defeat screen

### ISSUE THREAD

**Issue by ribbybibby** [ribbybibby/Grimm-Journey#20]
At the moment, when you lose you are brought back to the main menu kind of awkwardly. We should implement a defeat screen of some sort.

**Comment by HoboMechanistic** [comment]
1de345095e6eadd27e2a81e7a4281712735859d9 - This commit added a basic defeat screen with place holder assets. I'l close this bug off once the final assets are in. But the framework is complete :)

**Comment by HoboMechanistic** [comment]
This is now finalized and it looks super sexy :D Closing bug
