### ISSUE TITLE
[Audio] Add bwwaaarrrrp sound to the darkness

### ISSUE THREAD

**Issue by ribbybibby** [ribbybibby/Grimm-Journey#23]
By a lucky coincidence, the first track 'creepy woods' features a horn sound that coincides with the darkness coming on screen. This sounds awesome. We should rip that horn sound from the audio track and tie it to the darkness appearing on other levels.

**Comment by HoboMechanistic** [comment]
Legal-wise we are totally cool to do this. After I get the narration done I'll rip out this audio clip so we can make use of it :)

**Comment by HoboMechanistic** [comment]
I had some time so I did this. I have the audio clip on me, I'll add it in to a commit when I next push one

**Comment by HoboMechanistic** [comment]
In our latest build now ready to be used. Closing this.
