### ISSUE TITLE
[UI] Add some sort of HUD?

### ISSUE THREAD

**Issue by ribbybibby** [ribbybibby/Grimm-Journey#27]
Has the time come for us to introduce some HUD into the game?

- We are now topping up BBW's health with a proto-lifesteal mechanic; maybe we should add a health bar to communicate this to the player?

- We now have a cooldown on some of BBW's attacks, maybe we should add HUD cues to communicate this?

I think a cluttered HUD would detract from the fairly stripped back aesthetic of our game, so we should tread lightly. Also this will likely take ages, so it is more of a wishlist item at this point.

**Comment by HoboMechanistic** [comment]
Sounds good to me, maybe I'll give Laura a shout to come up with a design that suites the look and feel of the game. We need a wishlist tag :D

**Comment by ribbybibby** [comment]
Idea: we could attach a basic, rectangular quad to the top or bottom of the BBW and LRRH prefabs that would scale proportionally with the character's health. I have a few ideas on how to implement this that I'm going to play around with.

**Comment by ribbybibby** [comment]
I've added the health bars in b3f9ca237d3c6c550a8da51fcc64a7e2d1d5796c. They use red and green renderer.material color flashes to indicate damage and lifesteal. If we decide that this isn't in keeping with the aesthetic, it can easily be changed.

**Comment by ribbybibby** [comment]
I think the cooldown HUD would be too cluttered and we have another bug tracking UI anyway, so I'm going to close this one.
