### ISSUE TITLE
[Project] Should we make a Project Page?

### ISSUE THREAD

**Issue by HoboMechanistic** [ribbybibby/Grimm-Journey#42]
Hey guys, I thought I'd mention this before I spent anymore time on it. I mentioned to Rob1 a while ago that I was planning on making a project page, which would be a basic web page with GJ stuff on it.

I made a basic framework tonight (sans art assets and new CSS) with the following tabs - About / Media / Play / Contact.

The About section will explain the game and what it is (I currently use Laura's blog post she made on the Ludum Dare blog but we can easily change it if need be).

The Media section will be used to show off screenshots (currently three) and videos, videos of people playing etc.

Play will have a download link to a solid beta once I get off my arse and finish adding the narration -.-

Contact can have our deets (links to our blogs,sites etc) if you guys want. We can even have a little paragraph each to talk about who we are and what our interests are in terms of the project etc.

I think it's important that we have one solid place to show people our stuff. Submitting to Leftfield required me to hastily make a page to link them as at the moment GJ is all grape vined through blogs and links and repos. Which works, but people are lazy yo! Hopefully this will be a better solution and rather than try and explain to people we can just show em a link and BAM they know what GJ is about :)

I havn't made anything live yet since I wanted your feedbacks but if you guys want this I can host it on my site/domain for now? It would probably be a link like tinyflame.co.uk/GrimmJourney?

Any feedbacks, please give me a shout :D

**Comment by LMitch83** [comment]
A project page definitely sounds like a good idea! Having a single space for everything related to the game is handy for the reasons you mentioned, plus we can link to the Ludum Dare pages through it.

I think the menu headings you suggested are fine - we don't want to bombard people with stuff. Having said that, we could have a news section? Just a simple blog style page where we can post significant updates on the game, or call for additional testers, etc.

I'd also be happy for links to my blog to be put up on the site.

One thing I was thinking is that we could create an email address specifically for the game, rather than adding everyone's personal emails. Thoughts?

I'd also be happy for it to be hosted on your domain for the moment, but in the future it might be nice to have a separate domain (if it's not too expensive/annoying).

**Comment by ribbybibby** [comment]
Project page is definitely a good idea and I don't mind hosting it on your site. If it takes off, we can register a proper domain name for it to give it a profesh sheen.

**Comment by HoboMechanistic** [comment]
Sweet beans guys, I'll continue working on it then, it's pretty much done now. Just need some art assets to make it pretty. I'll host it once it's done and then get you guyses feedback on it. So we can change things. 

The text elements on the site are taken from a text file and then built into the page. So any of us can make changes to the site in terms of the text file, after that I'll just have to re-upload it to my host.

If we end up publishing this on some platform someplace in the future we can host it on a proper domain, I agree. Would be nice to have a shared one.

Could I ask for you guys to post your deets here? Links to blogs. I agree that it would be cool to have a GJ email, how would we go about setting one up? I suppose we could make a gmail account. Maybe I can register a SomethingSomething@GrimmJourney.com instead that we can share. Maybe through my hosting service - I'll look into our options and let you guys know.

Btw, off topic but check out this screenshot comparison: http://www.tinyflamedev.blogspot.co.uk/2015/02/grimm-journey-old-and-new.html :D

**Comment by LMitch83** [comment]
By details, do you mean our blog pages?:
http://funandwordgames.blogspot.co.uk

BTW, I burst out laughing on the train when I read your blog post.

**Comment by HoboMechanistic** [comment]
Yea that's what I mean :)

**Comment by HoboMechanistic** [comment]
Will close this and make a new bug to track project page creation.
