### ISSUE TITLE
[GameLogic] Replace old Character Swap pre-fabs/functionality

### ISSUE THREAD

**Issue by HoboMechanistic** [ribbybibby/Grimm-Journey#46]
We have to replace the character swaps on some of the levels. As some of them may be old and results in mass LRRH spawnage everywhere :D

**Comment by ribbybibby** [comment]
I can do this quickly tomorrow. It is just a matter of going through each level we have and reverting the Pickups back to the latest prefab.

**Comment by ribbybibby** [comment]
Will do this tomorrow... I promise.

**Comment by ribbybibby** [comment]
Fixed in 3159135e783dd516205c2677e301e67450f8360e

Finally got around to this!
