### ISSUE TITLE
[GameLogic] Fix Tree flying off of level (Right Hand Tree)

### ISSUE THREAD

**Issue by HoboMechanistic** [ribbybibby/Grimm-Journey#48]
Sometimes, the right hand side tree will go flying off into some strange direction. Maybe a character collides with it? Need to investigate.

**Comment by ribbybibby** [comment]
Fixed in 2d29ad5d77bba95799f165d14326310a3c39d413

The TreeR object was -0.8 on the Z Axis, rather than -5. Rectified that now.

**Comment by HoboMechanistic** [comment]
I knew it! :D
