### ISSUE TITLE
[Code] Add camera panning

### ISSUE THREAD

**Issue by HoboMechanistic** [ribbybibby/Grimm-Journey#49]
Rob1's idea and I think it's a good one. Adding camera panning will allow us to make bigger levels and this would make it easier to follow Laura's level designs as we won't be limited. 

A few things we can do and need to keep in mind if we do this are:
	Dealing with characters off screen
	Possibly adding in parallax effect at later stage to make things looks sexier

As Ludum Dare is over we no longer need to stick to the 'All on one screen' theme as previously required.

Rob1 said he'd try and look into this as time permits.

**Comment by ribbybibby** [comment]
I've added camera panning to the unused Moving Platform scene in 44b64775875ee6431ac300bdf0a31db8c91a276e. So far, the way it works is:

- The camera moves 1:1 with BBW
- The background moves 1:1 with the camera
- The orthographic size of the camera is adjusted as  (the original size set in the editor) + (the distance between the two characters / 10)

**Comment by ribbybibby** [comment]
I've committed two more camera implementations in 9d6cc4f4705eaf958bea5504932bbeea3242cdb4. If you go to the Moving Platform scene, you can adjust the 'lockMidVector' variable to 1, 2 or 3 in the inspector to change between all three methods.

I've also uploaded test builds for each of these methods to my website (linked below).

[Camera 1](http://www.ribbybibby.com/games/camtest/cam1/Cam_1.html) - moves 1:1 on the x-axis with the mid-vector between both characters, there is a slight 'tolerance' area on the y-axis, so the camera's pan is a little less snappy.

[Camera 2](http://www.ribbybibby.com/games/camtest/cam2/Cam_2.html) - moves 1:1 with the midVector on both axes, this way the camera follows both chars equally.

[Camera 3](http://www.ribbybibby.com/games/camtest/cam3/Cam_3.html) - moves 1:1 with BBW on both the x and y axis.

**Comment by ribbybibby** [comment]
Personally I prefer number 2.

**Comment by ribbybibby** [comment]
A few more thoughts on this sweeping change. 

1. No matter what camera dynamic we use, it is possible for either character to leave the other behind and for one or both to be off-screen or near the edge of the screen. In these cases, I think it would be neat to implement the 'swirling darkness' we talked about in the original docs which would spell impending doom. Initially I thought maybe a dark vignette kind of aura at the edges of the screen that rapidly grows? 

2. As the camera facilitates larger levels, with more upwards movement, we could look at increasing the speed of the darkness so it feels more present and dangerous.

3. We currently move the background in time with the camera, which actually looks kind of neat but unfortunately doesn't do the artist's wonderful backgrounds justice. Need to look into parallaxing or something similar, like Rob noted, to give the BG some depth.

4. I've added big black quads around the edge of the test level, so as to hide the uneven game elements the player doesn't need to see. This is more important with a moving camera and I think we should look into a pretty way of doing this bordering.

5. Relatedly, the camera allows us to make our levels a bit wider, if we so wish.

**Comment by HoboMechanistic** [comment]
From a functionality stand point number 2 makes sense since each play would be less dependant on the other to run around the level. 

What I like about camera three is that it limits the camera panning accross the level to the least mobile character. So this kind of contricts the players to make sure the wolf is guides without the need to force them to do so. But this is more of a design choice I think. Laura any input on this? :)

As for the other thoughts:-
1. How would this mechanic work? Say if LRRH was off screen, there would be an aura on that side of the screen and after X amount of time the player is killed? It sounds wicked either way just want to make sure I'm on the same page :D

2. This would be wicked, especially with your jump improvement and us fixing the BBW jump bug on controller. This should make things a bit more fast paced, which with bigger levels will be wicked fun I would imagine.

3. I would totes be up for this. It would mean that the background assets need to be stripped apart in their layers. But Stace wants to fine-tune a lot of the art assets anyhow so I think this won't be a problem. Will confirm with her. But its something we can look into. It would add a lot to the game.

4. Maybe we can add some kind of aura around the camera? Like when you take damage games these days, its got a red hue/tint on the side of the camera? Would be interesting to see how this could be done.

Any input on this design wise Laura?

**Comment by LMitch83** [comment]
Hey,

Some random, late-night thoughts:

We *could* allow the players to go off-screen and force the camera to stay on the BBW (who is the least mobile) - the Smash Bros games often do this, and have a little icon to show the player is at a certain side of the screen (above, below, left, right, etc. of the camera). I think this might be problematic, as the v. weak LLRH would be wandering off blindly into enemies without a way to get back to the camera. Unless you guys want to implement the 'press down to float through platforms' functionality, I think this would end up being frustrating - not being able to see where enemies are in addition to not being able to see the gaps between platforms would probably lead to ragequitting :).

I think the swirling darkness is a good way of restricting movement off-camera - it can be incorporated into the narrative that if characters are separated for too long, it triggers the darkness to chase them. However, I think we still need to be a bit more forceful in stopping players from going off-camera; it seems a bit unfair to have them die immediately from wandering too far.

If we have two mechanics in place, we could cover all eventualities.

Move camera when:
Both players are in the top or bottom 1/4 of the screen.
Only move the camera 1/4 up, so they remain in the centre of the screen - this allows for a player to slip off a platform during that transition and still be able to see how to get back up.

ALTERNATIVE 
Move camera when:
Both players are in the top or bottom 1/4 of the screen.
Move the camera up so the players are placed at the bottom of the screen.
Show a player icon in the rough direction they are off-camera, and have an urgent alert sound/visual to alert the other player so they rush to their aid.

I prefer the former in my head, as I think there's a lot of other urgent behaviour in the game as it is, but it might be worth trying them both out and seeing which feels right.

Trigger swirling darkness if: 
One player only spends more than 10 seconds at the top/bottom of the screen 
AND both characters are more than half a screen apart. 
I think that would be safe.

With regards to the levels themselves, I imagined they would only scroll up/down, and not left/right. Thoughts?

Oh, and I also like the aura at the edges of the screen idea - we would need to be careful that it doesn't interfere with the view of the swirling darkness, though. Maybe something like Tomb Raider, (where there are spatters around the screen) so the player can see damage is taking place, but it doesn't obscure all the edges of the screen.

**Comment by LMitch83** [comment]
Ooh - other thought: the 'alerting a player if one goes off-screen' alternative would hit issues if LRRH was trapped off-screen, and BBW can't jump to get to her. Another reason I think the former suggestion is a safer bet.

**Comment by ribbybibby** [comment]
I'm going to try implementing Laura's two camera idea as Camera 4 and 5. At that point we will probably be in a position to play test it and make a decision on what works best. We'll always have the option to change back to any of them further down the road. 

After that is done, I'll split the connected issues we've highlighted here into new bugs so this doesn't become a bumper bug.

**Comment by ribbybibby** [comment]
I added Camera 4 and 5 in 79a689ad2bd693f7b8b41ae4f22e6b2c99e3f057. I'll post links to some test builds in a second after I grab a cup of tea.

Personally I like the way these cameras feel, especially number 5. I think it encourages co-operation and also effectively splits the level into little sections, which could be cool from a level design standpoint. We do lose some of the dynamism of the first three, but I'm not sure that's necessarily a big loss.

**Comment by HoboMechanistic** [comment]
"With regards to the levels themselves, I imagined they would only scroll up/down, and not left/right. Thoughts?"
Yea this would follow the story narrative of climbing up the bean stalk. Camera can pan side to side maybe but the level progress should be heading upwards I feel.

Great work guys :) Looking forward to testing the new cams!

I very briefly looked into drawing decals on the camera (on screen) to indicate things like damage. Unfortunatly this is a Unity Pro deal. So we'd have to make our own one, which isn't out of the question. We can currently do it using UI textures I think, matching them to camera coords. But a better solution would be try and use shaders I think. I'll look into this some more.

**Comment by ribbybibby** [comment]
Test builds:
[Camera 4] (http://www.ribbybibby.com/games/camtest/cam4/Cam_4.html)
[Camera 5] (http://www.ribbybibby.com/games/camtest/cam5/Cam_5.html)

**Comment by ribbybibby** [comment]
I fixed a bug in CameraMove.cs in b2bb674df6c8a153dcf5101875d3112d85e2b358.

**Comment by ribbybibby** [comment]
Closed in fe66e80d172fdf657a2be87c4c50103deba1653f

I added the panning camera to the game cam prefab and updated all the scenes to use it properly. There is still more more to do (i.e #56) but I think I can close this bug. Any other camera stuff can be opened separately.
