### ISSUE TITLE
[Gameplay] Jumping is still too floaty

### ISSUE THREAD

**Issue by ribbybibby** [ribbybibby/Grimm-Journey#53]
Related to #14.

We noted during our first play testing session that the jumping still felt too floaty. 

Rob2 suggested that we add more gravity to a descending character so they fall to earth more quickly and suspend in mid-air less. The issue with this is that the way I implemented the airborne gravity accumulation means that you need to up the jump force to offset the increase in gravity, making it a bizarre juggling act.

One thing we discussed was to only have gravity increase on descent, so the character will be able to reach the peak of their jump easily but then come crashing down. I'm going to try this; but I also had an idea that we could increase airborne gravity force based on whether the 'Down' key is held or not. This would give control of the descent to the player, which might be neat.

I summation: I'm going to try adding extra gravitational force on 'Down' key press

**Comment by ribbybibby** [comment]
I added an incremental increase to gravity when the down key is pressed in the air. If we feel this is still too floaty and not immediate enough, I can hardcode a value so the char just drops down at an even force.

We need to play about with adjusting the public variable for gravity force so we can find a nice value.

**Comment by HoboMechanistic** [comment]
Nice one making in a public variable :D Will make testing much easier

**Comment by ribbybibby** [comment]
We found a value that worked quite nicely for LRRH while we were playtesting, I committed this in d9ce7387d9654251081715a03574e81bf019a536.

Closing. Any other adjustments aren't bugs, as the functionality for tweaking is all there.
