### ISSUE TITLE
[Graphics] Art assets showing up with lesser quality in-engine

### ISSUE THREAD

**Issue by HoboMechanistic** [ribbybibby/Grimm-Journey#59]
[Graphics] Art assets showing up with lesser quality in-engine

Stace makes all our assets, even the super tiny ones, in super huge resolution.

For obvious reasons I don't want to import a texture or decal thats huge then scale it down super tiny. This bloats the game and could cause performance issues (a guess on performance since I'm not sure how scaling works in terms of drawcalls and that stuff in Unity). For big art assets or important assets I tend to import bigger versions.

However Stace mentioned that she doesn't think her assets are looking right when comparing to the originals, which I agree with. They do seem to down scale quite a bit. 

I'm going to try and work with her to reach a decent solution to this. Thus far I have the following ideas, in order of most probably cause:

Ensure that the texture/decal is not being imported in a compressed format. Try setting to uncompressed if this is the case and see if there's any improvement.

Try importing two of the same assets at different resolutions and see how it impacts the look and feel

We currently use the Unity built in shaders. Specifically the Diffuse shader. This is kinda my go to shader since it does the basics in terms of rendering and lighting. The lighting is pretty basic with this shader and this might be contributing to the look of the graphics.

With regards to the shaders we could try a different shader, however none of the other buildt in shaders make sense to me. Unless we make use of bumpmapping / hightmapping (which we dont as we are sexy 2D people) or extensive use of lighting effects the other shaders would be overkill. I will however try out the Vertex lit shader since this is an upgrade from Diffuse in terms of performance and maybe this will mean we can have a higher resolution. I'll also play around with the Specular shader and see if lighting fixes this issue, or at least improves the over all look. I'll do this last after trying to obvious solutions though.

Will work with Stace on this.

**Comment by ribbybibby** [comment]
I watched a guide on making 2D games in Unity a few months ago and they recommended using the Unlit, or in our case Unlit Transparent shader, unless you want your art assets to respond to lighting. This supposedly offers the best performance because it does no passes on lighting and also displays the asset exactly as it is in the engine.

I just tested this briefly and can confirm that the white lines on BBW are more pronounced using this shader.

**Comment by ribbybibby** [comment]
Current shader:
![screen shot 2015-02-11 at 18 04 57](https://cloud.githubusercontent.com/assets/9870923/6153029/74c2e20c-b219-11e4-8b6c-df00bccf1418.png)

Sexy 'Unlit Transparent' shader:
![screen shot 2015-02-11 at 18 05 31](https://cloud.githubusercontent.com/assets/9870923/6153038/83937076-b219-11e4-8bea-5b70592b6c22.png)

**Comment by HoboMechanistic** [comment]
Dude, you have a link to the name of that guide? :D 

Nice one, I didn't think the diffuse shaders lighting were affecting it that much. Good to know! Using a specular shader would have made it even worse :o

**Comment by ribbybibby** [comment]
I updated the shader for the character assets in 0861fc0bbef42ef023659a8be35bf91aa470d35b. I left the background elements and the Victory object as I think they look better darker.

We have a bug tracking asset quality (#54) so I'm closing this.
