### ISSUE TITLE
[UI] Add instructive UI cues

### ISSUE THREAD

**Issue by ribbybibby** [ribbybibby/Grimm-Journey#6]
I think the consensus of the feedback we received on the LD site was that the game was 'confusing'. I think we could help this by adding small visual cues.

For instance:
- Add an arrow above the victory light that either persists for the whole level or disappears after a set amount of time
- Add an up-arrow or a jumping symbol above the BBW when his jumping ability is active, or perhaps his asset could 'glow' a bit?

**Comment by ribbybibby** [comment]
Tomorrow I'm going to have a go at adding the code for these with placeholder assets.

**Comment by ribbybibby** [comment]
I added UI to the transformative light in b9cd26fde033e34ed4853c195dbc8209b7e599ea. It will show when either BBW or LRRH are within a certain distance of the pickup. We just need a theatre mask from the artist to put in the place of the placeholder cube I'm using at the mo.

Left to do:
- Add a glow to BBW when he is able to jump (I think this is better than an arrow)
- Add an arrow to the Victory point

**Comment by HoboMechanistic** [comment]
Arrow example reference: http://www.vectorstock.com/royalty-free-vector/vintage-arrows-vector-979459

**Comment by ribbybibby** [comment]
I've added a glow to BBW in df61e601d77a1604e7237ccba9571f3cc55a10d5 which activates when LRRH is in contact with BBW.

See:
![screen shot 2015-01-24 at 18 27 54](https://cloud.githubusercontent.com/assets/9870923/5888444/d29af972-a3f6-11e4-8d64-f271b5580ffc.png)

We might want to look at finding a better asset for it but the code and objects are there in the editor. All it would take would be to swap out the material on it.

Left to do:
- Add an arrow to the Victory point

**Comment by frozenhowl** [comment]
Will create the 2 assests tonight : Arrow and Theatre masks
Will you need different rotations of the arrow as seperate assests at all or is this something you can rotate in the code? (if you need to change the arrows direction)

**Comment by ribbybibby** [comment]
We can flip assets in the editor like we do with the wolf etc. So just the one arrow should do.

**Comment by frozenhowl** [comment]
Sent Rob2 assests for the switcher and arrow

**Comment by HoboMechanistic** [comment]
Added to build in 3aa2987b0c9dc5d1c9e10f054cccf84f8ce649ba. I implemented the switcher already. Stace and I already discussed that it's pretty small. But we can use this for now until we implement the camera panning stuffs and see if it still needs improvement. Closing this for now :)
