### ISSUE TITLE
[Project] We need to think of a team name

### ISSUE THREAD

**Issue by HoboMechanistic** [ribbybibby/Grimm-Journey#62]
Hey guys, since we are going to set up an IndieDB account I figure it was about time we come up with a name. This way I can stop using my tinyflame name everywhere and then feeling terribly guilty about it.

Please post any ideas for a team name below :)

We can discuss and vote on a name after we all have time to provide some input.

Edit: For the sake of sanity lets say three potential names per person.

**Comment by HoboMechanistic** [comment]
Team Name idea: Superstar Jellyfish

:D

**Comment by ribbybibby** [comment]
Rob J and I stumbled upon 'Ternimals' (mis-spelling of Terminal).

Pros: sounds like an animal name, lends itself well to a cute kind of mascot creature

Con: easily mistaken for 'Terminal'.. looks like a mis-spelling (which it is)

**Comment by LMitch83** [comment]
Here are my three (terrible) suggestions:

Quadoperative (portmanteau of quad (our team) and cooperative (our game) )
Shadowturf (grows in the shade,)
Puppet Masters (because we control the shadow puppets)

I kind of like Superstar Jellyfish, and I echo Rob's feelings about Ternimals (cute, but looks misspelled. Plus my phone autocorrects it back to terminals).

**Comment by frozenhowl** [comment]
I like the Quadoperative one XD

depends if the names just for this project / future stuff we might do etc
but I'v got: (biased on just the 1 game team name atm)
Shadowjam
Bad Wolf Productions
Dapper Pigeon Entertainment   < That came from a random name generateor and I just had to post it

**Comment by LMitch83** [comment]
I actually really like Dapper Pigeon Entertainment...

**Comment by HoboMechanistic** [comment]
lol @ Dapper Pigeon Entertainment. Suits our locale I guess :P 

I also like Quadoperative. Ternimals does look a lot like Terminals .. it's a shame cause I think a little Ternimal would look adorable! :)

**Comment by LMitch83** [comment]
OK, should we gather a few names and take a vote? Unless a decision's already been made, in which case ignore me :).

**Comment by HoboMechanistic** [comment]
Decided on Dapper Pigeon :) closing
