### ISSUE TITLE
[Design] Enemy, Bosses and Level Elements additions to the wiki

### ISSUE THREAD

**Issue by LMitch83** [ribbybibby/Grimm-Journey#63]
Hi all,

In lieu of anywhere meaningful to upload it, I added a whole bunch of stuff concerning potential new (and existing) enemies, bosses and level elements on the wiki. I then noticed Rob DJ said this should be for finalised ideas only :). Are you guys okay for me to keep that stuff there for the moment as a reference point for discussion? I'm happy to update it as and when we make decisions on what to include/remove/amend.

**Comment by ribbybibby** [comment]
I don't mind keeping this stuff on the wiki but I think anything that is still up in the air should be clearly marked as so. 

Ideally, I think we'll want the wiki to be a reference 'bible' that we can use to make sure our work falls in line with the central vision.

**Comment by LMitch83** [comment]
Good point, Rob - I'll mark what's been agreed/not yet agreed tomorrow.

**Comment by HoboMechanistic** [comment]
Yea, don't take that to literally, spam it and mark it up if you feel the need. 

Basically we can post questions/thoughts here, in bugs, once agreed on we can post it in the Wiki and close the bug? :) The enemy stuff looks fine to me though and the bosses as well.

**Comment by LMitch83** [comment]
I added a note for the enemies/bosses not yet agreed, just to remind us all that these are still to be discussed. 

Happy to do as Rob DJ mentioned above in general.

**Comment by HoboMechanistic** [comment]
Good job Laura thanks. Added a design tag to this bug since it's not really a project bug :o Think that's a good way to keep things organised? :D

**Comment by HoboMechanistic** [comment]
Going to close this as we've dealt with this now and have a system in place. Let me know if this needs to be open.
